### ISSUE TITLE
Support for dropwizard 1.1.0

### ISSUE THREAD

**Issue by jmdesprez** [xvik/dropwizard-guicey-ext#1]
Hello,

Dropwizard 1.1.0 use jdbi 2.78 and current version of guicey-jdbi use 2.73.
If you try to use both in a project, you get in trouble because UnitHandleDing doesn't implement the new method "setContext".

It seems that forcing the version of jdbi to 2.73 is a valid workaround (at least the server start and simple request works) but I'm not sure it's a valid solution.

I've try to checkout the repository to make a pull request but because of the dependency management system, it's a bit complicated to change the version of dropwizard in the gradle :-/

Based on `org.skife.jdbi.v2.sqlobject.ConstantHandleDing` is seems that a valid implementation could be:
```
@Override
    public SqlObjectContext setContext(SqlObjectContext context) {
        final Handle handle = handleProvider.get();
        SqlObjectContext oldContext = handle.getSqlObjectContext();
        handle.setSqlObjectContext(context);
        return oldContext;
    }
```
*Disclaimer* I'm not a jdbi or guicey expert :)

I've compile guicey-jdbi 0.2.2-SNAPSHOT locally and this implementation seems ok (server start and dao seems ok)

**Comment by xvik** [comment]
Hi!

> it's a bit complicated to change the version of dropwizard in the gradle :-/

It's not gradle fault, and, generally, gradle dependency management is much better than maven,
Project imports guicey pom as BOM which transitively imports guice and dropwizard BOMs. The best way to override dropwizard version is to add dropwizrd bom directly in the root project (after guicey import).

I was sure I checked 1.1.0 compatibility, but indeed there is a problem. 
I will release guicey at its current state and then will release ext modules. 
Most likely, everything will be released before monday.

p.s. thank you for the proposed fix

**Comment by xvik** [comment]
[Released](https://github.com/xvik/dropwizard-guicey-ext/releases/tag/0.3.0)
