### ISSUE TITLE
Request: Can we opt out of getting the transaction isolation level when using `inCurrentTransaction` ?

### ISSUE THREAD

**Issue by mustafashabib** [xvik/dropwizard-guicey-ext#165]
Hey there

Firstly, let me thank you for building this library. We've found it immensely helpful.

We use the `@InTransaction` annotation in our codebase which ultimately cause us to run the database queries through [`inCurrentTransaction`](https://github.com/xvik/dropwizard-guicey-ext/blob/6141364a6680dc80677ecadd3d4e290481bd3cc3/guicey-jdbi3/src/main/java/ru/vyarus/guicey/jdbi3/tx/TransactionTemplate.java#L84) to utilize the same transaction. This works great from a functional standpoint. 

However, we notice that the method is checking the current transaction level of the handle by calling `getTransactionIsolationLevel` on the underlying connection. In our case, this uses the PgConnection from the `org.postgres.postgresql` lib for our database, which executes the query `SHOW TRANSACTION ISOLATION LEVEL` to get this level. 

<img width="955" alt="image" src="https://github.com/xvik/dropwizard-guicey-ext/assets/836482/6247a528-cc0a-432d-9e24-22d6190a4a3f">

In cases where a request is being handled that calls multiple methods decorated with `@InTransaction`, this causes many calls to `getTransactionIsolationLevel` and creates some overhead.

I'm curious if you've considered a way to cache the current isolation level for the currently used handle's connection for a period of time and only check the isolation level on the underlying connection when that time has expired. 

It would be a great addition from my perspective to provide an optional property to the `@InTransaction` annotation to let us specify this cache time. I'm happy to submit the pull request for this if you think it's a good idea. 

Thanks

**Comment by jonesetc** [comment]
alternatively, and hopefully more simple this could just be reordered to avoid the whole check if not needed https://github.com/xvik/dropwizard-guicey-ext/blob/6141364a6680dc80677ecadd3d4e290481bd3cc3/guicey-jdbi3/src/main/java/ru/vyarus/guicey/jdbi3/tx/TransactionTemplate.java#L84-L97

into:

```java
    private <T> T inCurrentTransaction(final TxConfig config, final TxAction<T> action) throws Exception {
        // mostly copies org.jdbi.v3.sqlobject.transaction.internal.TransactionDecorator logic
        final Handle h = manager.get();
        if (config.isLevelSet()) {
            final TransactionIsolationLevel currentLevel = h.getTransactionIsolationLevel();
            if (currentLevel != config.getLevel()) {
                throw new TransactionException("Tried to execute nested @Transaction(" + config.getLevel() + "), "
                    + "but already running in a transaction with isolation level " + currentLevel + ".");
            }
        }
        if (h.isReadOnly() && !config.isReadOnly()) {
            throw new TransactionException("Tried to execute a nested @Transaction(readOnly=false) "
                    + "inside a readOnly transaction");
        }
        return action.execute(h);
    }
```

Because `config.isLevelSet()` is false for the default case (`config.level == TransactionIsolationLevel.UNKNOWN`), moving that check to before the DB call and allowing it to short circuit would avoid the issue all together and not require any more complex caching.

**Comment by xvik** [comment]
5.9.1, 6.1.1 and 7.0.1 released with fix
