### ISSUE TITLE
Is there any new release planned for guicey-jdbi for jdbi3

### ISSUE THREAD

**Issue by nitirajrathore** [xvik/dropwizard-guicey-ext#2]
Hi,

I am trying to use guicey-jdbi with jdbi3 but I am getting errors like below. I think this is because guicey-jdbi is bringing in org.jdbi:jdbi:jar:2.78. If I change all my objects to use v2 version of jdbi lib and create abstract classes (as in jdbi v2) instead of Interfaces (required in jdbi v3), everything works fine.
Please let me know if you are planning to release this library's next version which is compatible with jdbi3. 

```
ERROR [2018-04-18 09:06:48,119] io.dropwizard.jersey.errors.LoggingExceptionMapper: Error handling a request: 63e2fac45299937e
! java.lang.NoSuchMethodError: java.lang.Object.findAll()Ljava/util/List;
! at org.skife.jdbi.v2.sqlobject.CloseInternalDoNotUseThisClass$$EnhancerByCGLIB$$5f8e55.CGLIB$findAll$8(<generated>)
! at org.skife.jdbi.v2.sqlobject.CloseInternalDoNotUseThisClass$$EnhancerByCGLIB$$5f8e55$$FastClassByCGLIB$$8d590e90.invoke(<generated>)
! at org.skife.jdbi.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
! at org.skife.jdbi.v2.sqlobject.PassThroughHandler.invoke(PassThroughHandler.java:34)
! at org.skife.jdbi.v2.sqlobject.SqlObject.invoke(SqlObject.java:224)
! at org.skife.jdbi.v2.sqlobject.SqlObject$3.intercept(SqlObject.java:133)
! at org.skife.jdbi.v2.sqlobject.CloseInternalDoNotUseThisClass$$EnhancerByCGLIB$$5f8e55.findAll(<generated>)
! at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
! at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
! at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
! at java.lang.reflect.Method.invoke(Method.java:498)
! at ru.vyarus.guicey.jdbi.installer.repository.RepositoryInstaller.lambda$install$0(RepositoryInstaller.java:56)
! at ru.vyarus.guicey.jdbi.tx.aop.TransactionalInterceptor.lambda$invoke$0(TransactionalInterceptor.java:26)
! at ru.vyarus.guicey.jdbi.tx.TransactionTemplate.lambda$inTransaction$0(TransactionTemplate.java:61)
! at org.skife.jdbi.v2.tweak.transactions.LocalTransactionHandler.inTransaction(LocalTransactionHandler.java:183)
! at org.skife.jdbi.v2.BasicHandle.inTransaction(BasicHandle.java:338)
! at ru.vyarus.guicey.jdbi.tx.TransactionTemplate.inTransaction(TransactionTemplate.java:61)
! at ru.vyarus.guicey.jdbi.tx.aop.TransactionalInterceptor.invoke(TransactionalInterceptor.java:24)
! at net.codingdemon.jdbitest.example.v3.resource.UserResource.findAll(UserResource.java:52)
! at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
! at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
! at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
! at java.lang.reflect.Method.invoke(Method.java:498)
```

**Comment by xvik** [comment]
Hi!

Yes, I plan to release jdbi3 ext module. I want to add separate module, like dropwizard did so there will be 2 jdbi ext modules.

Note that current jdbi2 ext module will not work with guice 4.2.0 and this will be fixed too (actually it just requires more recent [ext-annotations](https://github.com/xvik/guice-ext-annotations/releases/tag/1.3.0) dependency).

The bad news is time.. Right now I'm working on new guicey release and this will take one or two weeks (I hope). Only after that I'll start working on ext modules. So new ext release will be not earlier than May (middle or end).

**Comment by nitirajrathore** [comment]
@xvik : thanks for the update. I understand the time limitation and you are doing a great job. I tried doing it myself but could not make it work, because of my limited understanding of guice and jdbi.
Will wait for your update. 
Thanks.

**Comment by xvik** [comment]
[jdbi3 module](https://github.com/xvik/dropwizard-guicey-ext/tree/master/guicey-jdbi3) [released](https://github.com/xvik/dropwizard-guicey-ext/releases/tag/0.5.0). Tomorrow I will update guicey documentation and add jdbi3 example.
