### ISSUE TITLE
SPA for index that is not at root

### ISSUE THREAD

**Issue by novaterata** [xvik/dropwizard-guicey-ext#3]
I have a REST API where I wish to keep root as is, and serve an SPA at /app/index.html. the classpath location is /assets.  I tried:

    bootstrap.addBundle(SpaBundle.app("app", "/assets", "/app").build());

But it just behaved like plain AssetsBundle. Angular routing did not work. What am I missing?

**Comment by xvik** [comment]
If your application is in `src/main/resources/assets` then you should map it as
```java
bootstrap.addBundle(SpaBundle.app("app", "/assets", "/app").build());
```
So, for example,  `src/main/resources/assets/index.html` will be available as `http://localhost:8080/app/index.html`

**Comment by novaterata** [comment]
Sorry that was a typo, I had it configured like that

**Comment by xvik** [comment]
And if it was a typo in your example and your mapping is correct, then you need correct [base tag](https://angular.io/guide/router) in index.html (base href=/app)

**Comment by novaterata** [comment]
I did have base href as /app. Still just an OK with empty body. I finally got hash routing to work by using /app/index.html as the base href. It's less than ideal, but adequate since this is like a bonus app for demoing the API. So, I don't need this "fixed" anymore (if it was even broken), but I haven't found a single example of a dropwizard SPA configured on anything other than the root route, so I'm assuming it's just not getting tested by anyone. Oh well.

**Comment by xvik** [comment]
Just tried and everything works when base ends with a slash: `<base href="/app/">`.

**Comment by novaterata** [comment]
I tried it with /app/ as base href and as the 3rd parameter in SpaBundle.app. I tried with /app/ and /app, Everything I've tried I just get a blank page. Maybe it's the angular-routing as even hash routing doesn't work unless I make /app/index.html the base href. So I think your library isn't the culprit. Thanks for looking into it.
