### ISSUE TITLE
Unable to recover from db reboot due to transaction isolation level check

### ISSUE THREAD

**Issue by INRIX-daniel-weaver** [xvik/dropwizard-guicey-ext#35]
I currently am connected to an RDS cluster in AWS, where db servers can come and go due to auto-scaling. Whenever this happens, I get bad connections that remain in the pool which no longer correspond to physical connections.  This issue will persist until I perform a restart of the application.

This appears to be due to the check to get the transaction isolation level, as it doesn't appear to close with the underlying connection.

This is the error that I receive:

`
! java.sql.SQLException: PooledConnection has already been closed.
! at org.apache.tomcat.jdbc.pool.DisposableConnectionFacade.invoke(DisposableConnectionFacade.java:87)
! at com.sun.proxy.$Proxy95.getTransactionIsolation(Unknown Source)
! at org.jdbi.v3.core.Handle.getTransactionIsolationLevel(Handle.java:523)
! ... 72 common frames omitted
! Causing: org.jdbi.v3.core.transaction.UnableToManipulateTransactionIsolationLevelException: unable to access current setting
! at org.jdbi.v3.core.Handle.getTransactionIsolationLevel(Handle.java:525)
! at ru.vyarus.guicey.jdbi3.tx.TransactionTemplate.inCurrentTransaction(TransactionTemplate.java:87)
! at ru.vyarus.guicey.jdbi3.tx.TransactionTemplate.inTransaction(TransactionTemplate.java:69)
! at ru.vyarus.guicey.jdbi3.tx.aop.TransactionalInterceptor.invoke(TransactionalInterceptor.java:51)
! at com.inrix.fusion.nowcasting.pixel.service.PixelService.getPixelsFromEdges(PixelService.java:51)
! at com.inrix.fusion.nowcasting.pixel.resources.PixelResource.getPixelsFromEdges(PixelResource.java:130)
`

Here is my db configuration, which I've been changing a lot to experiment with timeouts and checks to work around the issue, but nothing as worked so far.

`
database:
  driverClass: org.postgresql.Driver
  url: xxxx
  user: xxxx
  password: xxxx
  maxSize: 1000
  checkConnectionOnBorrow: true
  checkConnectionOnReturn: true
  removeAbandoned: true
  maxConnectionAge: 60s
`

If this is not a bug, do you have any suggestions on how to work around this issue?

**Comment by xvik** [comment]
Try to specify `validationQuery` to explicitly validate connections before use ([docs](https://www.dropwizard.io/en/latest/manual/configuration.html#database)). Should help

**Comment by INRIX-daniel-weaver** [comment]
From the documentation, it appears that it is already set to SELECT 1. I explicitly set it anyways, and I the issue still remains. I tried setting the validation to the 50ms minimum, and I was still able to consistently reproduce the issue.

It does seem to happen less setting the validation internval to 50ms, but not sure if I'm just getting lucky. The problem is that once the application starts getting the  **SQLException: PooledConnection has already been closed.** error, it never recovers.

**Comment by xvik** [comment]
I simulated this error and probably there is a problem in unit tracking code [here](https://github.com/xvik/dropwizard-guicey-ext/blob/master/guicey-jdbi3/src/main/java/ru/vyarus/guicey/jdbi3/unit/UnitManager.java#L72)

```java
unit.get().close();
unit.remove();
```

In my case, jdbi handle didn't close properly and so handle is never removed from thread local.
But, this should only fail all further transactions that will appear in this exact thread and other threads should work. As I understand, in your case all threads stop working after a first incident.

Anyway, this is an intermediate result, I just have no time to properly test recover behavior (but will do it a later).

**Comment by xvik** [comment]
I used testcontainers with postgres and [toxiproxy](https://www.testcontainers.org/modules/toxiproxy/) to simulate connection problems and make sure the fix helps. Now application could recover. The only strange moment is that it will fail for (current pool size)x2 times before recovering (not sure why 2x, but it could be specific to test), anyway at least it recovers now eventually.

**Comment by xvik** [comment]
Fix [released](https://github.com/xvik/dropwizard-guicey-ext/releases/tag/5.1.0-2)
