### ISSUE TITLE
Request to add strictGroupsDeclaration option for guicey-validation

### ISSUE THREAD

**Issue by siwonred** [xvik/dropwizard-guicey-ext#69]
Guidey-validation does not have the `strictGroupsDeclaration` option.
So we're using guice-validator manually.
We want to strengthen the wrap function such as strictGroupsDeclaration option in guicey-validation.

**Comment by xvik** [comment]
Agree, missed this option in integration. Will add it in the next release (a new release should happen soon to test the new release process (without jcenter)).

**Comment by siwonred** [comment]
👍👍
